#version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: gateway.Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - redirector
      - monitor_service
  redirector:
    build:
      context: .
      dockerfile: redirector.Dockerfile
    container_name: redirector
    ports:
      - "8091:8091"
    networks:
      - app-network
  monitor_service:
    build:
      context: .
      dockerfile: monitor.service.Dockerfile
    container_name: monitor_service
    ports:
      - "8092:8092/udp"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

