name: smart_link_cmake_ci

on:
    push:
        branches: [ "main", "develop" ]
    pull_request:
        branches: [ "main", "develop" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: install gtest
              run: sudo apt-get install -y libgtest-dev libgmock-dev

    #        - name: install boost
    #          run: sudo apt-get install -y libboost-all-dev
    # install and cache dependencies
            - name: Cache boost
              uses: actions/cache@v1.0.3
              id: cache-boost
              with:
                path: "~/boost"
                key: libboost1.83-dev
            - name: Install boost
              env:
              CACHE_HIT: ${{steps.cache-boost.outputs.cache-hit}}
              run: |
              if [[ "$CACHE_HIT" == 'true' ]]; then
                sudo cp --force --recursive ~/boost/* /
              else
                sudo apt-get update && sudo apt-get install -yq libboost1.65-dev
                mkdir -p ~/boost
                for dep in libboost1.83-dev; do
                  dpkg -L $dep | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/boost/
                done
              fi

            - name: checkout
              uses: actions/checkout@v4
            
            - name: configure
              run: mkdir build; cd build; cmake ..;

            - name: build tests
              run: cd build; make;

            - name: run tests
              run: cd build/IoC_test; ls -all; ./ioc_test;
